apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/tls-acme: "true"
  name: animal-rescue-ingress
spec:
  tls:
    - hosts:
        - fluffy.spring.animalrescue.online
      secretName: animal-rescue-certs
    - hosts:
        - partner.spring.animalrescue.online
      secretName: partner-certs
  rules:
    - host: fluffy.spring.animalrescue.online
      http:
        paths:
          - backend:
              serviceName: animal-rescue
              servicePort: 80
    - host: partner.spring.animalrescue.online
      http:
        paths:
          - backend:
              serviceName: partner-adoption-center
              servicePort: 80
