apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

secretGenerator:
- name: cloud-dns-admin
  type: Opaque
  files:
  - secret/gcp-dns-account-credentials.json

generatorOptions:
  disableNameSuffixHash: true
