config:
  existingSecret: oauth2-internal-proxy-creds

extraArgs:
  whitelist-domain: .spring.animalrescue.online
  cookie-domain: .spring.animalrescue.online
  provider: oidc
  redirect-url: https://auth-internal.spring.animalrescue.online/oauth2/callback
  oidc-issuer-url: https://your.oidc.provider/oauth/token
  email-domain: "*"
  cookie-secure: false
image:
  tag: v6.0.0
ingress:
  enabled: true
  path: /
  hosts:
  - auth-internal.spring.animalrescue.online
  annotations:
#    cert-manager.io/issuer: gcloud-dns-issuer-1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
#    acme.cert-manager.io/http01-edit-in-place: "true"
  tls:
  - secretName: oauth2-proxy-https-cert
    hosts:
    - auth-internal.spring.animalrescue.online
