name: Test all

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 11.0.x, 12, 13 ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 12
    - run: ls -al
    - run: pwd
    - run: ./script/local.sh init
    - run: ./script/local.sh ci
